import type {
  LibraryControlDefinition,
  RibbonControlSize,
  RibbonPreviewMode,
  RibbonSubgroupSizeMode,
} from './types';

export const LOCAL_STORAGE_KEY = 'gispro-ribbon-designer-doc';

export const PREVIEW_MODES: RibbonPreviewMode[] = ['Large', 'Medium', 'Small', 'Collapsed'];

export const SUBGROUP_SIZE_MODES: RibbonSubgroupSizeMode[] = [
  'AlwaysLarge',
  'AlwaysMedium',
  'AlwaysSmall',
  'Default',
  'LargeThenMediumWhenMedium',
  'LargeThenMediumWhenSmall',
  'LargeThenSmallWhenMedium',
  'LargeThenSmallWhenSmall',
  'MediumThenSmallWhenMedium',
  'MediumThenSmallWhenSmall',
];

export const CONTROL_LIBRARY: LibraryControlDefinition[] = [
  {
    type: 'button',
    label: '按钮',
    shortDescription: '执行一次性命令，例如打开窗口、导出、计算。',
    supportedSizes: ['small', 'middle', 'large'],
    defaultCaption: '导出',
    defaultTooltip: '执行按钮命令',
    defaultBehavior: {
      commandType: 'button',
      className: 'ExportCommand',
      target: 'currentView',
      arguments: {},
    },
    defaultAiNotes: '单次触发的 Ribbon 按钮。',
    icon: { small: 'button16', large: 'button32' },
  },
  {
    type: 'tool',
    label: '交互工具',
    shortDescription: '进入地图交互状态，例如点击、框选、绘制。',
    supportedSizes: ['small', 'middle', 'large'],
    defaultCaption: '选择',
    defaultTooltip: '激活地图交互工具',
    defaultBehavior: {
      commandType: 'tool',
      className: 'SelectTool',
      target: 'map',
      arguments: {},
    },
    defaultAiNotes: '进入地图交互模式的工具。',
    icon: { small: 'tool16', large: 'tool32' },
  },
  {
    type: 'splitButton',
    label: '分裂按钮',
    shortDescription: '主命令加下拉候选命令。',
    supportedSizes: ['middle', 'large'],
    defaultCaption: '添加图层',
    defaultTooltip: '主命令与候选命令组合',
    defaultBehavior: {
      commandType: 'splitButton',
      className: 'AddLayerSplitButton',
      target: 'menu',
      arguments: {},
    },
    defaultAiNotes: '带主命令与下拉候选命令的组合按钮。',
    icon: { small: 'split16', large: 'split32' },
  },
  {
    type: 'toolPalette',
    label: '工具板',
    shortDescription: '一组同类工具的快速切换入口。',
    supportedSizes: ['middle', 'large'],
    defaultCaption: '绘制',
    defaultTooltip: '从一组工具中切换',
    defaultBehavior: {
      commandType: 'toolPalette',
      className: 'DrawPalette',
      target: 'map',
      arguments: {},
    },
    defaultAiNotes: '多个同类工具的集合入口。',
    icon: { small: 'palette16', large: 'palette32' },
  },
  {
    type: 'menu',
    label: '菜单',
    shortDescription: '展开多个命令项。',
    supportedSizes: ['small', 'middle', 'large'],
    defaultCaption: '选项',
    defaultTooltip: '展开菜单命令',
    defaultBehavior: {
      commandType: 'menu',
      className: 'OptionsMenu',
      target: 'menu',
      arguments: {},
    },
    defaultAiNotes: '包含多条命令项的菜单。',
    icon: { small: 'menu16', large: 'menu32' },
  },
  {
    type: 'gallery',
    label: '画廊',
    shortDescription: '以图块方式展示样式、模板、符号等。',
    supportedSizes: ['middle', 'large'],
    defaultCaption: '填充样式',
    defaultTooltip: '从图块中选择样式',
    defaultBehavior: {
      commandType: 'gallery',
      className: 'FillStyleGallery',
      target: 'selection',
      arguments: {},
    },
    defaultAiNotes: '用于样式、模板或符号的可视化选择。',
    icon: { small: 'gallery16', large: 'gallery32' },
  },
  {
    type: 'comboBox',
    label: '下拉框',
    shortDescription: '从列表中选择一个值，也可以动态加载。',
    supportedSizes: ['middle', 'large'],
    defaultCaption: '行政区划',
    defaultTooltip: '从列表中选择值',
    defaultBehavior: {
      commandType: 'comboBox',
      className: 'AdminSelector',
      target: 'selection',
      arguments: {},
    },
    defaultAiNotes: '通过列表选择参数值的控件。',
    icon: { small: 'combo16', large: 'combo32' },
  },
  {
    type: 'editBox',
    label: '输入框',
    shortDescription: '输入文本、数字、路径、参数。',
    supportedSizes: ['middle', 'large'],
    defaultCaption: 'C:\\Data\\Project.gdb',
    defaultTooltip: '录入参数值',
    defaultBehavior: {
      commandType: 'editBox',
      className: 'PathEditor',
      target: 'form',
      arguments: {},
    },
    defaultAiNotes: '用于录入文本、数字或路径参数。',
    icon: { small: 'edit16', large: 'edit32' },
  },
  {
    type: 'checkBox',
    label: '复选框',
    shortDescription: '开关型选项，勾选或取消勾选。',
    supportedSizes: ['small', 'middle'],
    defaultCaption: '显示注记',
    defaultTooltip: '切换开关状态',
    defaultBehavior: {
      commandType: 'checkBox',
      className: 'ToggleLabel',
      target: 'settings',
      arguments: {},
    },
    defaultAiNotes: '用于布尔开关选项。',
    icon: { small: 'check16', large: 'check32' },
  },
];

export const SIZE_LABELS: Record<RibbonControlSize, string> = {
  small: '小',
  middle: '中',
  large: '大',
};
